// Analysis slice
export {
  default as analysisReducer,
  loadAnalysisResults,
  addAnalysisResult,
  updateAnalysisResult,
  deleteAnalysisResult,
  importAnalysisData,
  clearUserData,
  clearError as clearAnalysisError,
  updateStats,
  setLastSaved,
  selectAnalysisResults,
  selectAnalysisStats,
  selectAnalysisLoading,
  selectAnalysisError,
  selectIsInitialized,
  selectLastSaved,
  selectResultsByCategory,
  selectResultsByParameter,
  selectLatestResult,
  selectChartData,
} from './analysisSlice';

// UI slice
export {
  default as uiReducer,
  setSelectedCategory,
  clearSelectedCategory,
  openAddForm,
  closeAddForm,
  openImportDialog,
  closeImportDialog,
  openExportDialog,
  closeExportDialog,
  setLoading,
  setError,
  clearError as clearUIError,
  setTheme,
  toggleTheme,
  setSidebarOpen,
  toggleSidebar,
  addNotification,
  removeNotification,
  clearAllNotifications,
  showSuccessNotification,
  showErrorNotification,
  showWarningNotification,
  showInfoNotification,
  resetUI,
  selectSelectedCategory,
  selectIsAddFormOpen,
  selectIsImportDialogOpen,
  selectIsExportDialogOpen,
  selectUILoading,
  selectUIError,
  selectTheme,
  selectSidebarOpen,
  selectNotifications,
} from './uiSlice';
