import type { AnalysisResult, HistoricalDataSet } from '../types';

export const HISTORICAL_DATA: HistoricalDataSet = {
  patientInfo: {
    name: 'Ирина Н.',
    birthDate: '1999-11-11',
    gender: 'female',
  },
  lastUpdated: '2025-06-03',
  results: [
    // Ферритин от 02.06.2025
    {
      id: 'ferritin_2025_06_02',
      categoryId: 'blood_biochemistry',
      parameterId: 'ferritin',
      value: 28.6,
      unit: 'мкг/л',
      date: '2025-06-02',
      notes: 'Фолликулярная фаза цикла',
      isHistorical: true,
    },

    // Общий анализ крови от 02.06.2025
    {
      id: 'wbc_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'wbc',
      value: 5.3,
      unit: 'x10^9/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'rbc_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'rbc',
      value: 4.63,
      unit: 'x10^12/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'hgb_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'hgb',
      value: 136,
      unit: 'г/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'hct_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'hct',
      value: 40.8,
      unit: '%',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'mcv_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'mcv',
      value: 88.1,
      unit: 'фл',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'mch_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'mch',
      value: 29.4,
      unit: 'пг',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'mchc_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'mchc',
      value: 333,
      unit: 'г/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'rdw_cv_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'rdw_cv',
      value: 12.5,
      unit: '%',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'plt_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'plt',
      value: 256.0,
      unit: 'x10^9/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'esr_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'esr',
      value: 17,
      unit: 'мм/час',
      date: '2025-06-02',
      notes: 'Немного выше нормы',
      isHistorical: true,
    },
    {
      id: 'neutrophils_abs_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'neutrophils_abs',
      value: 2.6,
      unit: 'x10^9/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'lymphocytes_abs_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'lymphocytes_abs',
      value: 1.9,
      unit: 'x10^9/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'monocytes_abs_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'monocytes_abs',
      value: 0.69,
      unit: 'x10^9/л',
      date: '2025-06-02',
      notes: 'Немного выше нормы',
      isHistorical: true,
    },
    {
      id: 'eosinophils_abs_2025_06_02',
      categoryId: 'blood_general',
      parameterId: 'eosinophils_abs',
      value: 0.13,
      unit: 'x10^9/л',
      date: '2025-06-02',
      isHistorical: true,
    },

    // Витамин D от 02.06.2025
    {
      id: 'vitamin_d_2025_06_02',
      categoryId: 'vitamins',
      parameterId: 'vitamin_d',
      value: 18.7,
      unit: 'нг/мл',
      date: '2025-06-02',
      notes: 'Недостаточность витамина D',
      isHistorical: true,
    },

    // Гормоны от 03.06.2025
    {
      id: 'dhea_s_2025_06_03',
      categoryId: 'hormones',
      parameterId: 'dhea_s',
      value: 237.2,
      unit: 'мкг/дл',
      date: '2025-06-03',
      notes: 'Фолликулярная фаза цикла',
      isHistorical: true,
    },
    {
      id: 'oh_progesterone_2025_06_03',
      categoryId: 'hormones',
      parameterId: 'oh_progesterone',
      value: 1.12,
      unit: 'нг/мл',
      date: '2025-06-03',
      notes:
        'Немного выше нормы, взят на 4-й день после приёма двух таблеток Дюфастона',
      isHistorical: true,
    },

    // Глюкоза от 02.06.2025
    {
      id: 'glucose_2025_06_02',
      categoryId: 'blood_biochemistry',
      parameterId: 'glucose',
      value: 4.46,
      unit: 'ммоль/л',
      date: '2025-06-02',
      isHistorical: true,
    },
    {
      id: 'glucose_2024_12_26',
      categoryId: 'blood_biochemistry',
      parameterId: 'glucose',
      value: 5.6,
      unit: 'ммоль/л',
      date: '2024-12-26',
      notes: 'ГУЗ "Брестская городская поликлиника N 3"',
      isHistorical: true,
    },
    {
      id: 'glucose_2023_05_11',
      categoryId: 'blood_biochemistry',
      parameterId: 'glucose',
      value: 4.6,
      unit: 'ммоль/л',
      date: '2023-05-11',
      notes: 'ГУЗ "Брестская городская поликлиника N 3"',
      isHistorical: true,
    },
    // Гематологический анализ крови

    // 26.12.2024
    {
      id: 'rbc_2024_12_26',
      categoryId: 'blood_general',
      parameterId: 'rbc',
      value: 4.73,
      unit: 'x10^12/л',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'hgb_2024_12_26',
      categoryId: 'blood_general',
      parameterId: 'hgb',
      value: 141,
      unit: 'г/л',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'hct_2024_12_26',
      categoryId: 'blood_general',
      parameterId: 'hct',
      value: 43,
      unit: '%',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'plt_2024_12_26',
      categoryId: 'blood_general',
      parameterId: 'plt',
      value: 240,
      unit: 'x10^9/л',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'wbc_2024_12_26',
      categoryId: 'blood_general',
      parameterId: 'wbc',
      value: 9.3,
      unit: 'x10^9/л',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'esr_2024_12_26',
      categoryId: 'blood_general',
      parameterId: 'esr',
      value: 10,
      unit: 'мм/час',
      date: '2024-12-26',
      isHistorical: true,
    },

    // 15.10.2024
    {
      id: 'rbc_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'rbc',
      value: 4.66,
      unit: 'x10^12/л',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'hgb_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'hgb',
      value: 141,
      unit: 'г/л',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'hct_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'hct',
      value: 41,
      unit: '%',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'plt_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'plt',
      value: 200,
      unit: 'x10^9/л',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'wbc_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'wbc',
      value: 11.03,
      unit: 'x10^9/л',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'neutrophils_abs_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'neutrophils_abs',
      value: 6,
      unit: 'x10^9/л',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'esr_2024_10_15',
      categoryId: 'blood_general',
      parameterId: 'esr',
      value: 32,
      unit: 'мм/час',
      date: '2024-10-15',
      isHistorical: true,
    },

    // 15.02.2024
    {
      id: 'rbc_2024_02_15',
      categoryId: 'blood_general',
      parameterId: 'rbc',
      value: 4.74,
      unit: 'x10^12/л',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'hgb_2024_02_15',
      categoryId: 'blood_general',
      parameterId: 'hgb',
      value: 145,
      unit: 'г/л',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'hct_2024_02_15',
      categoryId: 'blood_general',
      parameterId: 'hct',
      value: 40,
      unit: '%',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'plt_2024_02_15',
      categoryId: 'blood_general',
      parameterId: 'plt',
      value: 239,
      unit: 'x10^9/л',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'wbc_2024_02_15',
      categoryId: 'blood_general',
      parameterId: 'wbc',
      value: 7.0,
      unit: 'x10^9/л',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'esr_2024_02_15',
      categoryId: 'blood_general',
      parameterId: 'esr',
      value: 15,
      unit: 'мм/час',
      date: '2024-02-15',
      isHistorical: true,
    },

    // 11.05.2023
    {
      id: 'rbc_2023_05_11',
      categoryId: 'blood_general',
      parameterId: 'rbc',
      value: 5.0,
      unit: 'x10^12/л',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'hgb_2023_05_11',
      categoryId: 'blood_general',
      parameterId: 'hgb',
      value: 147,
      unit: 'г/л',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'hct_2023_05_11',
      categoryId: 'blood_general',
      parameterId: 'hct',
      value: 43,
      unit: '%',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'plt_2023_05_11',
      categoryId: 'blood_general',
      parameterId: 'plt',
      value: 267,
      unit: 'x10^9/л',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'wbc_2023_05_11',
      categoryId: 'blood_general',
      parameterId: 'wbc',
      value: 7.0,
      unit: 'x10^9/л',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'esr_2023_05_11',
      categoryId: 'blood_general',
      parameterId: 'esr',
      value: 10,
      unit: 'мм/час',
      date: '2023-05-11',
      isHistorical: true,
    },
    // 26.12.2024
    {
      id: 'urine_density_2024_12_26',
      categoryId: 'urinalysis',
      parameterId: 'urine_density',
      value: 1010,
      unit: '',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'urine_urobilinogen_2024_12_26',
      categoryId: 'urinalysis',
      parameterId: 'urine_urobilinogen',
      value: '3.4',
      unit: '',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'urine_ph_2024_12_26',
      categoryId: 'urinalysis',
      parameterId: 'urine_ph',
      value: 5.0,
      unit: '',
      date: '2024-12-26',
      isHistorical: true,
    },
    {
      id: 'urine_nitrites_2024_12_26',
      categoryId: 'urinalysis',
      parameterId: 'urine_nitrites',
      value: 'отриц.',
      unit: '',
      date: '2024-12-26',
      isHistorical: true,
    },

    // 15.10.2024
    {
      id: 'urine_density_2024_10_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_density',
      value: 1015,
      unit: '',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'urine_epithelial_2024_10_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_epithelial',
      value: '1-2',
      unit: '',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'urine_leukocytes_2024_10_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_leukocytes',
      value: '1-2',
      unit: '',
      date: '2024-10-15',
      isHistorical: true,
    },
    {
      id: 'urine_protein_2024_10_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_protein',
      value: '0',
      unit: '',
      date: '2024-10-15',
      isHistorical: true,
    },

    // 15.02.2024
    {
      id: 'urine_density_2024_02_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_density',
      value: 1010,
      unit: '',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'urine_epithelial_2024_02_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_epithelial',
      value: '3-4',
      unit: '',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'urine_leukocytes_2024_02_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_leukocytes',
      value: '2-3',
      unit: '',
      date: '2024-02-15',
      isHistorical: true,
    },
    {
      id: 'urine_protein_2024_02_15',
      categoryId: 'urinalysis',
      parameterId: 'urine_protein',
      value: '0',
      unit: '',
      date: '2024-02-15',
      isHistorical: true,
    },

    // 20.06.2023
    {
      id: 'urine_density_2023_06_20',
      categoryId: 'urinalysis',
      parameterId: 'urine_density',
      value: 1010,
      unit: '',
      date: '2023-06-20',
      isHistorical: true,
    },
    {
      id: 'urine_transparency_2023_06_20',
      categoryId: 'urinalysis',
      parameterId: 'urine_transparency',
      value: 'прозрачная',
      unit: '',
      date: '2023-06-20',
      isHistorical: true,
    },
    {
      id: 'urine_epithelial_2023_06_20',
      categoryId: 'urinalysis',
      parameterId: 'urine_epithelial',
      value: '0-1',
      unit: '',
      date: '2023-06-20',
      isHistorical: true,
    },
    {
      id: 'urine_leukocytes_2023_06_20',
      categoryId: 'urinalysis',
      parameterId: 'urine_leukocytes',
      value: '1-2',
      unit: '',
      date: '2023-06-20',
      isHistorical: true,
    },

    // 11.05.2023
    {
      id: 'urine_epithelial_2023_05_11',
      categoryId: 'urinalysis',
      parameterId: 'urine_epithelial',
      value: '5-7',
      unit: '',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'urine_leukocytes_2023_05_11',
      categoryId: 'urinalysis',
      parameterId: 'urine_leukocytes',
      value: '30-40',
      unit: '',
      date: '2023-05-11',
      isHistorical: true,
    },
    {
      id: 'urine_protein_2023_05_11',
      categoryId: 'urinalysis',
      parameterId: 'urine_protein',
      value: '0',
      unit: '',
      date: '2023-05-11',
      isHistorical: true,
    },

    {
      id: 'aptt_2024_10_21',
      categoryId: 'hemostasis',
      parameterId: 'aptt',
      value: 36.8,
      unit: 'с',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'inr_2024_10_21',
      categoryId: 'hemostasis',
      parameterId: 'inr',
      value: 1.06,
      unit: '',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'fibrinogen_2024_10_21',
      categoryId: 'hemostasis',
      parameterId: 'fibrinogen',
      value: 3.9,
      unit: 'г/л',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'pt_2024_10_21',
      categoryId: 'hemostasis',
      parameterId: 'pt',
      value: 14.2,
      unit: 'с',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'prot_complex_activity_2024_10_21',
      categoryId: 'hemostasis',
      parameterId: 'prot_complex_activity',
      value: 78,
      unit: '%',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'aptt_ratio_2024_10_21',
      categoryId: 'hemostasis',
      parameterId: 'aptt_ratio',
      value: 1.42,
      unit: '',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'glucose_ogtt_2025_06_02_1316',
      categoryId: 'blood_biochemistry',
      parameterId: 'glucose_ogtt',
      value: 5.9,
      unit: 'ммоль/л',
      date: '2025-06-02',
      notes: 'ОГТТ (2 ч), взят в 13:16',
      isHistorical: true,
    },
    {
      id: 'shbg_2025_06_02',
      categoryId: 'hormones',
      parameterId: 'shbg',
      value: 67.3,
      unit: 'нмоль/л',
      date: '2025-06-02',
      notes: '',
      isHistorical: true,
    },
    {
      id: 'amh_2025_06_02',
      categoryId: 'hormones',
      parameterId: 'amh',
      value: 3.61,
      unit: 'нг/мл',
      date: '2025-06-02',
      notes: '',
      isHistorical: true,
    },
    {
      id: 'androstenedione_2025_06_02',
      categoryId: 'hormones',
      parameterId: 'androstenedione',
      value: 1.893,
      unit: 'нг/мл',
      date: '2025-06-02',
      notes: '',
      isHistorical: true,
    },
    // 07.02.2024 — ПЦР-тест на ВПЧ высокого онкогенного риска (типы 16, 18, 45)
    {
      id: 'hpv_vkr_2024_02_07',
      categoryId: 'gynecology',
      parameterId: 'hpv_test',
      value: 'не обнаружено',
      unit: '',
      date: '2024-02-07',
      notes: 'Не обнаружено ВПЧ ВКР типов 16, 18, 45 (качественный ПЦР-тест)',
      isHistorical: true,
    },

    // 04.06.2025 — Обобщённый ПЦР-тест на ВПЧ высокого риска (панель ВКР)
    {
      id: 'hpv_vkr_2025_06_04',
      categoryId: 'gynecology',
      parameterId: 'hpv_test',
      value: 'не обнаружено',
      unit: '',
      date: '2025-06-04',
      notes:
        'Не обнаружено ВПЧ ВКР (суммарное определение генотипов: 16, 18, 31, 33, 35, 39, 45, 51, 52, 56, 58, 59, 66, 68)',
      isHistorical: true,
    },
    // 12.06.2025 — ТТГ, Free T4 и Free T3
    {
      id: 'ttg_2025_06_12',
      categoryId: 'hormones',
      parameterId: 'ttg',
      value: 0.124,
      unit: 'мкМЕ/мл',
      date: '2025-06-12',
      notes: 'Референс 0.27–4.2 мкМЕ/мл — чуть ниже нормы',
      isHistorical: true,
    },
    {
      id: 'ft4_2025_06_12',
      categoryId: 'hormones',
      parameterId: 'ft4',
      value: 22.8,
      unit: 'пмоль/л',
      date: '2025-06-12',
      notes: 'Референс 12–22 пмоль/л — слегка выше нормы',
      isHistorical: true,
    },
    {
      id: 'ft3_2025_06_12',
      categoryId: 'hormones',
      parameterId: 'ft3',
      value: 6.13,
      unit: 'пмоль/л',
      date: '2025-06-12',
      notes: 'Референс 3.1–6.8 пмоль/л — в норме',
      isHistorical: true,
    },
    {
      id: 'fsh_2025_06_10',
      categoryId: 'hormones',
      parameterId: 'fsh',
      value: 10.28,
      unit: 'мМЕ/мл',
      date: '2025-06-10',
      notes: 'ФСГ (фолликулярная фаза), реф. 1.8–11.3 мМЕ/мл',
      isHistorical: true,
    },
    {
      id: 'lh_2025_06_10',
      categoryId: 'hormones',
      parameterId: 'lh',
      value: 5.7,
      unit: 'мМЕ/мл',
      date: '2025-06-10',
      notes: 'ЛГ (фолликулярная фаза), реф. 1.1–8.7 мМЕ/мл',
      isHistorical: true,
    },
    {
      id: 'prolactin_2025_06_10',
      categoryId: 'hormones',
      parameterId: 'prolactin',
      value: 400.0,
      unit: 'мМЕ/л',
      date: '2025-06-10',
      notes: 'Пролактин (фолликулярная фаза), реф. 67–726 мМЕ/л',
      isHistorical: true,
    },
    {
      id: 'estradiol_2025_06_10',
      categoryId: 'hormones',
      parameterId: 'estradiol',
      value: 32.8,
      unit: 'пг/мл',
      date: '2025-06-10',
      notes: 'Эстрадиол (фолликулярная фаза), реф. 30–100 пг/мл',
      isHistorical: true,
    },
    {
      id: 'testosterone_total_2025_06_10',
      categoryId: 'hormones',
      parameterId: 'testosterone_total',
      value: 2.18,
      unit: 'нмоль/л',
      date: '2025-06-10',
      notes: 'Общий тестостерон (фолликулярная фаза), реф. 0.06–0.82 нмоль/л',
      isHistorical: true,
    },
    {
      id: 'ttg_2025_06_10',
      categoryId: 'hormones',
      parameterId: 'ttg',
      value: 0.08,
      unit: 'мкМЕ/мл',
      date: '2025-06-10',
      notes: 'ТТГ (фолликулярная фаза), реф. 0.40–4.20 мкМЕ/мл',
      isHistorical: true,
    },
    // 14.06.2025 — аутоантитела к щитовидке
    {
      id: 'a_tpo_2025_06_14',
      categoryId: 'hormones',
      parameterId: 'a_tpo',
      value: 272.7,
      unit: 'МЕ/мл',
      date: '2025-06-14',
      notes: 'Антитела к TPO, реф.: 0.0001–34 МЕ/мл',
      isHistorical: true,
    },
    {
      id: 'a_tg_2025_06_14',
      categoryId: 'hormones',
      parameterId: 'a_tg',
      value: 576.7,
      unit: 'МЕ/мл',
      date: '2025-06-14',
      notes:
        'Антитела к Tg, реф. взрослых: до 115 МЕ/мл; беременных — триместр 1 ≤454, 2 ≤166, 3 ≤177',
      isHistorical: true,
    },
    {
      id: 'anti_tshr_2025_06_14',
      categoryId: 'hormones',
      parameterId: 'anti_tshr',
      value: 0.895,
      unit: 'МЕ/л',
      date: '2025-06-14',
      notes:
        'Антитела к TSH-рецептору, реф. здоровых: ≤1.22; с болезн. щж: ≤1.53; с не леч. Базедовой: ≤1.75',
      isHistorical: true,
    },
    {
      id: 'urea_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'urea',
      value: 4.6,
      unit: 'ммоль/л',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'creatinine_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'creatinine',
      value: 78,
      unit: 'мкмоль/л',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'crp_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'crp',
      value: 2.1,
      unit: 'мг/л',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'aslo_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'aslo',
      value: 185,
      unit: 'IU/mL',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'ast_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'ast',
      value: 24,
      unit: 'U/L',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'alt_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'alt',
      value: 18,
      unit: 'U/L',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'ldh_2025_06_15',
      categoryId: 'blood_biochemistry',
      parameterId: 'ldh',
      value: 156,
      unit: 'U/L',
      date: '2024-10-21',
      isHistorical: true,
    },
    {
      id: 'tsh_2024_06_03',
      categoryId: 'hormones',
      parameterId: 'ttg',
      value: 3.59,
      unit: 'мкМЕ/мл',
      date: '2024-06-03',
      isHistorical: true,
    },
    {
      id: 'total_protein_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'total_protein',
      value: 75,
      unit: 'г/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'uric_acid_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'uric_acid',
      value: 4.6,
      unit: 'ммоль/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'ferritin_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'ferritin',
      value: 32,
      unit: 'мкг/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'glucose_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'glucose',
      value: 4.96,
      unit: 'ммоль/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'alkaline_phosphatase_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'alkaline_phosphatase',
      value: 63,
      unit: 'U/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'iron_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'iron',
      value: 7.6,
      unit: 'мкмоль/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'calcium_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'calcium',
      value: 2.35,
      unit: 'ммоль/л',
      date: '2024-06-03',
      isHistorical: true,
      notes: 'Точная дата неизвестна',
    },
    {
      id: 'cholesterol_2024_06_03',
      categoryId: 'blood_biochemistry',
      parameterId: 'cholesterol',
      value: 3.98,
      unit: 'ммоль/л',
      date: '2024-06-03',
      notes: 'Точная дата неизвестна',
      isHistorical: true,
    },

    // === Гормональный анализ 03.06.2024 ===
    {
      id: 'prolactin_2024_06_03',
      categoryId: 'hormones',
      parameterId: 'prolactin',
      value: 606.1,
      unit: 'нг/мл',
      date: '2024-06-03',
      notes: '28.59 нг/мл(было - выше нормы 28.53) × 21.2 → мМЕ/л',
      isHistorical: true,
    },
    {
      id: 'testosterone_total_2024_06_03',
      categoryId: 'hormones',
      parameterId: 'testosterone_total',
      value: 1.41,
      unit: 'нг/мл',
      date: '2024-06-03',
      notes: '',
      isHistorical: true,
    },
    {
      id: 'estradiol_2024_06_03',
      categoryId: 'hormones',
      parameterId: 'estradiol',
      value: 44,
      unit: 'пг/мл',
      date: '2024-06-03',
      notes: '',
      isHistorical: true,
    },
    {
      id: 'lh_2024_06_03',
      categoryId: 'hormones',
      parameterId: 'lh',
      value: 1.78,
      unit: 'мЕд/мл',
      date: '2024-06-03',
      notes: '',
      isHistorical: true,
    },
    {
      id: 'fsh_2024_06_03',
      categoryId: 'hormones',
      parameterId: 'fsh',
      value: 6.01,
      unit: 'мЕд/мл',
      date: '2024-06-03',
      notes: '',
      isHistorical: true,
    },
  ],
};

// Функция для получения исторических данных
export const getHistoricalData = (): HistoricalDataSet => {
  return HISTORICAL_DATA;
};

// Функция для добавления новых исторических данных
export const addHistoricalResult = (
  newResult: Omit<AnalysisResult, 'id' | 'isHistorical'>
) => {
  const result: AnalysisResult = {
    ...newResult,
    id: `${newResult.parameterId}_${newResult.date.replace(/-/g, '_')}`,
    isHistorical: true,
  };

  HISTORICAL_DATA.results.push(result);
  HISTORICAL_DATA.lastUpdated = new Date().toISOString().split('T')[0];

  return result;
};
