import type { Parameter } from '../types/analysis';

export const PARAMETERS: Parameter[] = [
  // ===== ОБЩИЙ АНАЛИЗ КРОВИ =====
  {
    id: 'wbc',
    name: 'Лейкоциты (WBC)',
    unit: 'x10^9/л',
    normalRange: { min: 4.0, max: 9.0 },
    category: 'blood_general',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'rbc',
    name: 'Эритроциты (RBC)',
    unit: 'x10^12/л',
    normalRange: {
      femaleRange: { min: 3.7, max: 4.7 },
      maleRange: { min: 4.0, max: 5.1 },
    },
    category: 'blood_general',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'hgb',
    name: 'Гемоглобин (HGB)',
    unit: 'г/л',
    normalRange: {
      femaleRange: { min: 120, max: 150 },
      maleRange: { min: 130, max: 170 },
    },
    category: 'blood_general',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'esr',
    name: 'Скорость оседания эритроцитов (СОЭ)',
    unit: 'мм/час',
    normalRange: {
      femaleRange: { min: 2, max: 15 },
      maleRange: { min: 2, max: 10 },
    },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'hct',
    name: 'Гематокрит (HCT)',
    unit: '%',
    normalRange: {
      femaleRange: { min: 33, max: 46 },
      maleRange: { min: 39, max: 49 },
    },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'mcv',
    name: 'Средний объем эритроцита (MCV)',
    unit: 'фл',
    normalRange: { min: 78, max: 98 },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'mch',
    name: 'Среднее содержание гемоглобина (MCH)',
    unit: 'пг',
    normalRange: { min: 27, max: 32 },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'mchc',
    name: 'Средняя концентрация гемоглобина (MCHC)',
    unit: 'г/л',
    normalRange: { min: 320, max: 360 },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'rdw_cv',
    name: 'Ширина распределения эритроцитов (RDW-CV)',
    unit: '%',
    normalRange: { min: 11.5, max: 14.5 },
    category: 'blood_general',
    importance: 'low',
    isNumeric: true,
  },
  {
    id: 'plt',
    name: 'Тромбоциты (PLT)',
    unit: 'x10^9/л',
    normalRange: { min: 150, max: 450 },
    category: 'blood_general',
    importance: 'high',
    isNumeric: true,
  },

  // Лейкоцитарная формула
  {
    id: 'neutrophils_abs',
    name: 'Нейтрофилы (абс.)',
    unit: 'x10^9/л',
    normalRange: { min: 1.7, max: 7.7 },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'lymphocytes_abs',
    name: 'Лимфоциты (абс.)',
    unit: 'x10^9/л',
    normalRange: { min: 1.2, max: 3.5 },
    category: 'blood_general',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'monocytes_abs',
    name: 'Моноциты (абс.)',
    unit: 'x10^9/л',
    normalRange: { min: 0.09, max: 0.6 },
    category: 'blood_general',
    importance: 'low',
    isNumeric: true,
  },
  {
    id: 'eosinophils_abs',
    name: 'Эозинофилы (абс.)',
    unit: 'x10^9/л',
    normalRange: { min: 0.04, max: 0.35 },
    category: 'blood_general',
    importance: 'low',
    isNumeric: true,
  },

  // ===== БИОХИМИЯ КРОВИ =====
  {
    id: 'glucose',
    name: 'Глюкоза',
    unit: 'ммоль/л',
    normalRange: { min: 3.8, max: 6.1 },
    category: 'blood_biochemistry',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'glucose_ogtt',
    name: 'Глюкоза через 2 ч после нагрузки',
    unit: 'ммоль/л',
    normalRange: { min: 3.8, max: 7.8 },
    category: 'blood_biochemistry',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'ferritin',
    name: 'Ферритин',
    unit: 'мкг/л',
    normalRange: {
      femaleRange: { min: 5.5, max: 94.0 },
      maleRange: { min: 12, max: 300 },
    },
    category: 'blood_biochemistry',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'urea',
    name: 'Мочевина',
    unit: 'ммоль/л',
    normalRange: { min: 2.3, max: 8.4 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'creatinine',
    name: 'Креатинин',
    unit: 'мкмоль/л',
    normalRange: { min: 40, max: 110 },
    category: 'blood_biochemistry',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'crp',
    name: 'С-реактивный белок (СРБ)',
    unit: 'мг/л',
    normalRange: { min: 0, max: 5 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'aslo',
    name: 'Анти-стрептолизин О (АСЛО)',
    unit: 'IU/mL',
    normalRange: { min: 0, max: 200 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'ast',
    name: 'Аспартатаминотрансфераза (AST)',
    unit: 'U/L',
    normalRange: { min: 3, max: 41 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'alt',
    name: 'Аланинаминотрансфераза (ALT)',
    unit: 'U/L',
    normalRange: { min: 3, max: 50 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'ldh',
    name: 'Лактатдегидрогеназа (LDH)',
    unit: 'U/L',
    normalRange: { min: 100, max: 253 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'total_protein',
    name: 'Общий белок',
    unit: 'г/л',
    normalRange: { min: 64, max: 83 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'alkaline_phosphatase',
    name: 'Щелочная фосфатаза',
    unit: 'U/л',
    normalRange: { min: 20, max: 220 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'iron',
    name: 'Железо',
    unit: 'мкмоль/л',
    normalRange: { min: 9, max: 28 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'calcium',
    name: 'Кальций',
    unit: 'ммоль/л',
    normalRange: { min: 2.1, max: 2.6 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'cholesterol',
    name: 'Холестерин общий',
    unit: 'ммоль/л',
    normalRange: { min: 2.5, max: 5.2 },
    category: 'blood_biochemistry',
    importance: 'medium',
    isNumeric: true,
  },

  // ===== ГОРМОНЫ =====
  {
    id: 'dhea_s',
    name: 'Дегидроэпиандростерон-сульфат (ДГЭА-С)',
    unit: 'мкг/дл',
    normalRange: { femaleRange: { min: 18.0, max: 391.0 } },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'oh_progesterone',
    name: '17-гидроксипрогестерон',
    unit: 'нг/мл',
    normalRange: { min: 0.1, max: 0.8, cycleDependent: true },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'ttg',
    name: 'Тиреотропный гормон (ТТГ)',
    unit: 'мЕд/л',
    normalRange: { min: 0.4, max: 4.0 },
    category: 'hormones',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'prolactin',
    name: 'Пролактин',
    unit: 'нг/мл',
    normalRange: {
      femaleRange: { min: 67.0, max: 726.0 },
      cycleDependent: true,
    },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'lh',
    name: 'Лютеинизирующий гормон (ЛГ)',
    unit: 'мЕд/мл',
    normalRange: { femaleRange: { min: 2.4, max: 12.6 }, cycleDependent: true },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'fsh',
    name: 'Фолликулостимулирующий гормон (ФСГ)',
    unit: 'мЕд/мл',
    normalRange: { femaleRange: { min: 3.5, max: 12.5 }, cycleDependent: true },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'estradiol',
    name: 'Эстрадиол',
    unit: 'пг/мл',
    normalRange: { femaleRange: { min: 12.5, max: 166 }, cycleDependent: true },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'testosterone_total',
    name: 'Общий тестостерон',
    unit: 'нг/мл',
    normalRange: { femaleRange: { min: 0.5, max: 4.3 } },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'androstenedione',
    name: 'Андростендион',
    unit: 'нг/мл',
    normalRange: { femaleRange: { min: 0.7, max: 2.7 } },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'shbg',
    name: 'Глобулин, связывающий половые гормоны (ГСПГ)',
    unit: 'нмоль/л',
    normalRange: { femaleRange: { min: 26.1, max: 110 } },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'amh',
    name: 'Антимюллеров гормон (АМГ)',
    unit: 'нг/мл',
    normalRange: { femaleRange: { min: 1.0, max: 6.0 } },
    category: 'hormones',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'ft4',
    name: 'Тироксин свободный (T4 св.)',
    unit: 'пмоль/л',
    normalRange: { min: 12, max: 22 },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'ft3',
    name: 'Трийодтиронин свободный (T3 св.)',
    unit: 'пмоль/л',
    normalRange: { min: 3.1, max: 6.8 },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'a_tpo',
    name: 'Антитела к пероксидазе щитовидной железы (АТПО)',
    unit: 'МЕ/мл',
    normalRange: { min: 0.0001, max: 34 },
    category: 'hormones',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'a_tg',
    name: 'Антитела к тиреоглобулину (АТТГ)',
    unit: 'МЕ/мл',
    normalRange: { min: 0.0001, max: 115 },
    category: 'hormones',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'anti_tshr',
    name: 'Антитела к TSH-рецептору (Anti-TSHR)',
    unit: 'МЕ/л',
    normalRange: { min: 0.0001, max: 1.22 },
    category: 'hormones',
    importance: 'medium',
    isNumeric: true,
  },

  // ===== ВИТАМИНЫ =====
  {
    id: 'vitamin_d',
    name: 'Витамин D общий',
    unit: 'нг/мл',
    normalRange: {
      min: 30,
      max: 100,
      reference:
        '<20 - дефицит; 20-29 - недостаточность; 30-100 - оптимальный уровень',
    },
    category: 'vitamins',
    importance: 'high',
    isNumeric: true,
  },

  // ===== ГИНЕКОЛОГИЧЕСКИЕ АНАЛИЗЫ =====
  {
    id: 'hpv_test',
    name: 'Анализ на ВПЧ инфекции',
    unit: '',
    normalRange: { reference: 'не обнаружено' },
    category: 'gynecology',
    importance: 'high',
    isNumeric: false,
  },
  {
    id: 'femoflor_screen',
    name: 'Фемофлор скрин',
    unit: '',
    normalRange: { reference: 'нормоценоз' },
    category: 'gynecology',
    importance: 'medium',
    isNumeric: false,
  },

  // ===== ЦИТОЛОГИЯ =====
  {
    id: 'liquid_cytology',
    name: 'Жидкостная цитология',
    unit: '',
    normalRange: { reference: 'NILM (норма)' },
    category: 'cytology',
    importance: 'high',
    isNumeric: false,
  },

  // ===== КЛИНИЧЕСКИЙ АНАЛИЗ МОЧИ =====
  {
    id: 'urine_density',
    name: 'Отн. плотность',
    unit: '',
    normalRange: { reference: '1005–1030' },
    category: 'urinalysis',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'urine_ph',
    name: 'pH мочи',
    unit: '',
    normalRange: { min: 4.5, max: 8.0 },
    category: 'urinalysis',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'urine_protein',
    name: 'Белок',
    unit: '',
    normalRange: { reference: 'отсутствует' },
    category: 'urinalysis',
    importance: 'high',
    isNumeric: false,
  },
  {
    id: 'urine_nitrites',
    name: 'Нитриты',
    unit: '',
    normalRange: { reference: 'отсутствуют' },
    category: 'urinalysis',
    importance: 'medium',
    isNumeric: false,
  },
  {
    id: 'urine_urobilinogen',
    name: 'Уробилиноген',
    unit: '',
    normalRange: { reference: '0.2–1.0 мг/л' },
    category: 'urinalysis',
    importance: 'low',
    isNumeric: false,
  },
  {
    id: 'urine_epithelial',
    name: 'Эпителий плоский',
    unit: '',
    normalRange: { reference: 'до 5–10 в п/зр' },
    category: 'urinalysis',
    importance: 'low',
    isNumeric: false,
  },

  {
    id: 'urine_leukocytes',
    name: 'Лейкоциты',
    unit: '',
    normalRange: { reference: 'до 3–5 в п/зр' },
    category: 'urinalysis',
    importance: 'medium',
    isNumeric: false,
  },

  // ===== Гоместозиограмма =====
  {
    id: 'aptt',
    name: 'АЧТВ',
    unit: 'с',
    normalRange: { min: 25, max: 35 },
    category: 'hemostasis',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'inr',
    name: 'МНО (INR)',
    unit: '',
    normalRange: { min: 0.9, max: 1.2 },
    category: 'hemostasis',
    importance: 'high',
    isNumeric: true,
  },
  {
    id: 'fibrinogen',
    name: 'Фибриноген',
    unit: 'г/л',
    normalRange: { min: 2.0, max: 4.0 },
    category: 'hemostasis',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'pt',
    name: 'ПВ (PT)',
    unit: 'с',
    normalRange: { min: 11, max: 14 },
    category: 'hemostasis',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'prot_complex_activity',
    name: 'Актив. протромб. компл.',
    unit: '%',
    normalRange: { min: 80, max: 120 },
    category: 'hemostasis',
    importance: 'medium',
    isNumeric: true,
  },
  {
    id: 'aptt_ratio',
    name: 'R-АЧТВ',
    unit: '',
    normalRange: { min: 0.8, max: 1.2 },
    category: 'hemostasis',
    importance: 'low',
    isNumeric: true,
  },
];

// Получение параметра по ID
export const getParameterById = (id: string): Parameter | undefined => {
  return PARAMETERS.find((param) => param.id === id);
};

// Получение параметров по категории
export const getParametersByCategory = (categoryId: string): Parameter[] => {
  return PARAMETERS.filter((param) => param.category === categoryId);
};
